title: "Further Study Required"
author: "dmartinezphd"
#description: "<b style=\"color: #f45;\">Daniel's information site and Further Study Required blog</b>"
description: "Daniel M. Martínez, PhD <br>Engineer, Scientist, Author <br>"Further Study Required"<br>[Privacy](https://dmartinezphd.github.io/privacy.md)<br>©2022 All rights reserved."
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: true     # show article excerpts on the home page
show_frame: false       # adds a gray frame to the site
show_sidebar: true     # show a sidebar instead of the usual header
minimal: true           # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}

  - {file: "index.md", title: "Home"}
  - {file: "blog.md", title: "Blog"}
  # - {file: "projects.md", title: "projects"}
  - {file: "about.md", title: "About Me"}
  # - {file: "tags.html", title: "tags"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  # - {title: You accept Privacy Policy by entering site, url: "https://dmartinezphd.github.io/privacy/"}
  - {title: email, icon: envelope, url: "mailto:daniel@randomwalkresearch.com"}
  - {title: github, icon: github, url: "https://github.com/dmartinezphd"}
  - {title: linkedin, icon: linkedin, url: "https://www.linkedin.com/in/dmartinezphd/"}
  # - {icon: rss, url: "/feed.xml"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
