title: "Daniel Martínez: Engineer, Scientist, Author"
author: "dmartinezphd"
#description: "<b style=\"color: #f45;\">Daniel's information site and blog</b>"
description: "How to reach me, and where to find me on socials"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: true     # show article excerpts on the home page
show_frame: false       # adds a gray frame to the site
show_sidebar: false     # show a sidebar instead of the usual header
minimal: true           # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  
  - {file: "README.md", title: "about me"}
  - {file: "randomwalk.md", "random walk research"}
  - {file: "index.html", title: "back to blog"}
 

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:daniel@randomwalkresearch.com"}
  - {title: Github, icon: github, url: "https://github.com/dmartinezphd"}
  - {title: LinkedIn, icon: linkedin, url: "https://www.linkedin.com/in/danielmartinezphd/"}
  # - {title: Subscribe, icon: rss, url: "/feed.xml"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
